### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by ValentynChepiha** [ValentynChepiha/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by MrMizerakl** [comment]
Hi! I'm a full stack developer with years of experience designing, developing applications and modeling databases. I strive to create applications that would satisfy the wishes of the customer and be easy to use.
